const photos = { about:'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=1400&q=85', program:'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1400&q=85', nature:'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=1400&q=85', people:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1400&q=85' }
const data = {
  'tentang-kami':{kicker:'Tentang Kami',title:'Dari ruang belajar,<br /><i>untuk kehidupan.</i>',desc:'Fitrah Tumbuh adalah social enterprise yang menumbuhkan manusia melalui pendidikan berbasis potensi, kedekatan dengan alam, dan kolaborasi komunitas.',image:photos.about,labels:['Sejarah Schole Fitrah','Visi & Misi','Wilayah Bandung–Sumedang'],section:'Jejak kami dimulai dari keyakinan sederhana: setiap manusia hadir dengan potensi yang layak ditemukan.'},
  filosofi:{kicker:'Filosofi Fitrah',title:'Setiap anak tumbuh<br /><i>dengan caranya sendiri.</i>',desc:'Kami memandang pendidikan sebagai proses menemani anak mengenali fitrahnya—akal, rasa, tubuh, dan kontribusinya bagi sesama.',image:photos.nature,labels:['Fitrah Keimanan','Fitrah Belajar','Fitrah Bakat'],section:'Pendidikan yang baik tidak menyeragamkan jalan, melainkan membantu tiap anak menemukan pijakannya.'},
  program:{kicker:'Program Fitrah Tumbuh',title:'Ruang belajar yang<br /><i>hidup dan bermakna.</i>',desc:'Program untuk anak, pemuda, keluarga, dan ibu rumah tangga yang menghubungkan pembelajaran dengan pengalaman nyata.',image:photos.program,labels:['Calistung & Literasi','Belajar Bersama Alam','Healing Farm','Hiking & Family Camp','Magang Pemuda','Inkubasi UMKM'],section:'Pilih program sesuai tahap tumbuh dan kebutuhan komunitas Anda.'},
  edukasi:{kicker:'Pusat Edukasi',title:'Belajar bisa dimulai<br /><i>dari mana saja.</i>',desc:'Koleksi sumber belajar untuk keluarga, pendidik, dan komunitas yang ingin bertumbuh secara sadar.',image:photos.program,labels:['Artikel','Ebook','Modul','Video','Worksheet','Download Center'],section:'Materi praktis yang bisa dibaca, ditonton, dan digunakan kembali di rumah maupun ruang belajar.'},
  galeri:{kicker:'Galeri Kegiatan',title:'Momen kecil yang<br /><i>menjadi cerita besar.</i>',desc:'Potret proses belajar, bermain, berkebun, dan bergerak bersama di Bandung dan Sumedang.',image:photos.people,labels:['Outdoor Class','Healing Farm','Family Camp','Kelas Literasi','Magang Pemuda','UMKM Binaan'],section:'Setiap foto menyimpan rasa ingin tahu, keberanian mencoba, dan pertemuan yang bermakna.'},
  portofolio:{kicker:'Portofolio Program',title:'Dampak yang tumbuh<br /><i>bersama komunitas.</i>',desc:'Dokumentasi program yang memperlihatkan proses, capaian, dan suara orang-orang yang bergerak bersama Fitrah Tumbuh.',image:photos.nature,labels:['Dokumentasi Foto','Video Kegiatan','Dampak Program','Testimoni','Statistik Program'],section:'Bukan hanya angka—di balik setiap capaian ada keluarga, sekolah, dan komunitas yang bertumbuh.'},
  kolaborasi:{kicker:'Mitra Pentahelix',title:'Kebaikan tumbuh lebih jauh<br /><i>saat dikerjakan bersama.</i>',desc:'Kami berkolaborasi dengan sekolah, pemerintah, komunitas, dunia usaha, dan media untuk membangun dampak yang berkelanjutan.',image:photos.people,labels:['Logo Mitra','Bentuk Kerja Sama','Dokumentasi','Capaian Program','Impact Story'],section:'Ruang kolaborasi terbuka bagi setiap pihak yang ingin menghadirkan pendidikan yang membumi.'},
  dampak:{kicker:'Dashboard Dampak',title:'Mengukur yang tumbuh,<br /><i>merayakan yang berarti.</i>',desc:'Gambaran dampak Fitrah Tumbuh dari program, kolaborasi, dan gerakan yang kami jalankan bersama.',image:photos.about,labels:['1.240 Peserta','48 Sekolah Mitra','12 Program Berjalan','7 Kota/Kabupaten','116 Relawan','32 Kolaborator','186 Total Kegiatan'],section:'Data ini adalah mockup dashboard dampak dan akan diperbarui secara berkala seiring gerakan yang bertumbuh.'},
  kontak:{kicker:'Kontak',title:'Ada cerita yang ingin<br /><i>ditumbuhkan bersama?</i>',desc:'Tim Fitrah Tumbuh siap menyambut kebutuhan program, kolaborasi, maupun pertanyaan Anda.',image:photos.people,labels:['Learning Center Bandung','Healing Farm Sumedang','WhatsApp','Instagram @fitrahtumbuh'],section:'Mari mulai percakapan yang baik.'}
}
export default function InteriorPage({page,navigate}){const p=data[page]||data.program;const impact=page==='dampak';return <section className="inside-page"><div className="inside-hero"><img className="inside-photo" src={p.image} alt="Kegiatan Fitrah Tumbuh"/><div className="inside-photo-overlay"></div><div className="inside-copy"><p className="eyebrow"><span></span>{p.kicker}</p><h1 dangerouslySetInnerHTML={{__html:p.title}}></h1><p>{p.desc}</p><a className="button" href="https://wa.me/6285156916211?text=Halo%20Fitrah%20Tumbuh%2C%20saya%20tertarik%20untuk%20mengetahui%20lebih%20lanjut%20mengenai%20program%20belajar%20dan%20kegiatan%20di%20Fitrah%20Tumbuh." target="_blank" rel="noreferrer">Hubungi kami <span>↗</span></a></div></div><section className={impact?'content-section impact-dashboard':'content-section'}><p className="eyebrow"><span></span> Jelajahi</p><h2>{p.section}</h2><div className="content-grid">{p.labels.map((label,index)=><article key={label}><span>{String(index+1).padStart(2,'0')}</span><h3>{label}</h3><p>{impact?'Data dampak terkini Fitrah Tumbuh':'Temukan cerita dan informasi selengkapnya.'}</p><b>→</b></article>)}</div></section><section className="inside-bottom"><p className="eyebrow"><span></span> Fitrah Tumbuh</p><h2>Hal baik selalu dimulai<br/>dari langkah yang dekat.</h2><button className="text-button" onClick={()=>navigate('beranda')}>← Kembali ke beranda</button></section></section>}
